### ISSUE TITLE
请问如何设置为每次request请求时，随机切换可用的节点？

### ISSUE THREAD

**Issue by Linkfufu** [Rain-kl/glider_guid#1]
感谢开发此项目，按照步骤，已配置成功！
想请问下：如何设置为每次request请求时，随机选择一个可用的机场节点？

**Comment by Rain-kl** [comment]
我只是介绍此项目如何使用，并未参与glider的开发。随机选择一个可用的机场节点可以通过配置config文件中的[节点选择策略](https://github.com/Rain-kl/glider_guid41asd4asd#轮询模式rr)来实现
