### ISSUE TITLE
运行无反应

### ISSUE THREAD

**Issue by corsgoo** [Rain-kl/glider_guid#4]
将clash内配置文件全部复制到config.yml内
运行订阅转换.py
我安装vscode，安装了py插件和本机安装了python。加载了yml和转换。py文件，在vscode里面运行转换文件怎么没反应呢？报错：[{
	"resource": "/P:/软路由/glider转换文件夹/glider_guid41asd4asd-master/订阅转换.py",
	"message": "无法从源解析导入“yaml”",，老板你给的那个粘贴的yaml文件不能加载进去运行哇。应该怎么处理呢

**Comment by Rain-kl** [comment]
你的yaml解析库没有安装正确,请尝试`pip3 install pyyaml`
