### ISSUE TITLE
请教大神。

### ISSUE THREAD

**Issue by valucn** [Rain-kl/glider_guid#5]
2024/09/19 20:30:58 server.go:99: [http] 127.0.0.1:49675 <-> checkip.amazonaws.com:443 via tls.10.node-for-bigairport.win:11443, relay error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:07 server.go:96: [http] 127.0.0.1:49684 <-> checkip.amazonaws.com:443 [c] via tls.11.node-for-bigairport.win:22443
2024/09/19 20:31:13 server.go:99: [http] 127.0.0.1:49684 <-> checkip.amazonaws.com:443 via tls.11.node-for-bigairport.win:22443, relay error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:15 group.go:263: [check] main: 0000000000000000000000000035.agroup-node-for-bigairport.sbs:38755(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:15 group.go:263: [check] main: 0000000000000000000000000040.agroup-node-for-bigairport.sbs:38760(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:15 group.go:263: [check] main: tls.04.node-for-bigairport.win:23443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:15 group.go:263: [check] main: 0000000000000000000000000034.agroup-node-for-bigairport.sbs:38754(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:16 group.go:263: [check] main: tls.16.node-for-bigairport.win:12443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:16 group.go:263: [check] main: tls.03.node-for-bigairport.win:12443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:16 group.go:263: [check] main: tls.18.node-for-bigairport.win:22443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:16 group.go:263: [check] main: tls.13.node-for-bigairport.win:44443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:16 group.go:263: [check] main: tls.01.node-for-bigairport.win:11443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:17 group.go:263: [check] main: tls.09.node-for-bigairport.win:55443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:17 group.go:263: [check] main: 0000000000000000000000000037.agroup-node-for-bigairport.sbs:38757(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:17 group.go:263: [check] main: tls.10.node-for-bigairport.win:11443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:17 group.go:263: [check] main: tls.92.node-for-bigairport.win:23443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:17 group.go:263: [check] main: 0000000000000000000000000039.agroup-node-for-bigairport.sbs:38759(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:18 group.go:263: [check] main: tls.05.node-for-bigairport.win:33443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:18 group.go:263: [check] main: tls.19.node-for-bigairport.win:33443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:18 group.go:263: [check] main: tls.17.node-for-bigairport.win:11443(0), FAILED. error: [vmess] error in DecodeRespHeader: read tcp 192.168.73.56:49711->35.76.118.191:11443: wsarecv: An existing connection was forcibly closed by the remote host.
2024/09/19 20:31:18 group.go:263: [check] main: tls.87.node-for-bigairport.win:45443(0), FAILED. error: dial tcp :0->172.233.80.77:45443: i/o timeout
2024/09/19 20:31:18 group.go:263: [check] main: tls.06.node-for-bigairport.win:443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:19 group.go:263: [check] main: tls.14.node-for-bigairport.win:14443(0), FAILED. error: [vmess] error in DecodeRespHeader: read tcp 192.168.73.56:49720->18.182.33.212:14443: wsarecv: An existing connection was forcibly closed by the remote host.
2024/09/19 20:31:19 group.go:263: [check] main: 0000000000000000000000000036.agroup-node-for-bigairport.sbs:38756(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:19 group.go:263: [check] main: tls.93.node-for-bigairport.win:34443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:19 group.go:263: [check] main: tls.11.node-for-bigairport.win:22443(0), FAILED. error: [vmess] error in DecodeRespHeader: read tcp 192.168.73.56:49709->35.78.178.49:22443: wsarecv: An existing connection was forcibly closed by the remote host.
2024/09/19 20:31:20 group.go:263: [check] main: tls.02.node-for-bigairport.win:443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:22 group.go:263: [check] main: 0000000000000000000000000033.agroup-node-for-bigairport.sbs:38753(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:23 group.go:263: [check] main: tls.12.node-for-bigairport.win:33443(0), FAILED. error: [vmess] error in DecodeRespHeader: read tcp 192.168.73.56:49726->35.78.207.84:33443: wsarecv: An existing connection was forcibly closed by the remote host.
2024/09/19 20:31:23 group.go:263: [check] main: tls.98.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->172.233.80.187:443: i/o timeout
2024/09/19 20:31:25 group.go:263: [check] main: tls.90.node-for-bigairport.win:443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:27 server.go:96: [http] 127.0.0.1:49733 <-> checkip.amazonaws.com:443 [c] via tls.12.node-for-bigairport.win:33443
2024/09/19 20:31:27 group.go:263: [check] main: tls.97.node-for-bigairport.win:45443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:27 group.go:263: [check] main: tls.88.node-for-bigairport.win:56443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:29 group.go:263: [check] main: 0000000000000000000000000032.agroup-node-for-bigairport.sbs:38752(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:29 group.go:263: [check] main: tls.94.node-for-bigairport.win:443(0), FAILED. error: [vmess] error in DecodeRespHeader: read tcp 192.168.73.56:49717->139.162.80.199:443: i/o timeout
2024/09/19 20:31:30 group.go:263: [check] main: tls.82.node-for-bigairport.win:12443(0), FAILED. error: dial tcp :0->139.162.80.218:12443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.84.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->139.162.80.245:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 0000000000000000000000000038.agroup-node-for-bigairport.sbs:38758(0), FAILED. error: dial tcp :0->54.151.203.180:38758: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.86.node-for-bigairport.win:34443(0), FAILED. error: dial tcp :0->172.233.80.244:34443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.99.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->172.233.80.214:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.15.node-for-bigairport.win:55443(0), FAILED. error: dial tcp :0->13.231.217.167:55443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.95.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->139.162.80.205:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 1.1.1.1:65535(0), FAILED. error: dial tcp :0->1.1.1.1:65535: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 1.1.1.1:65535(0), FAILED. error: dial tcp :0->1.1.1.1:65535: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 0000000000000000000000000031.agroup-node-for-bigairport.sbs:38751(0), FAILED. error: dial tcp :0->18.163.183.14:38751: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.20.node-for-bigairport.win:44443(0), FAILED. error: dial tcp :0->13.115.137.51:44443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 1.1.1.1:65535(0), FAILED. error: dial tcp :0->1.1.1.1:65535: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.96.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->172.233.80.106:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.85.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->139.162.80.192:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.08.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->52.198.175.35:443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.91.node-for-bigairport.win:12443(0), FAILED. error: dial tcp :0->139.162.80.60:12443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: 1.1.1.1:65535(0), FAILED. error: dial tcp :0->1.1.1.1:65535: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.07.node-for-bigairport.win:34443(0), FAILED. error: dial tcp :0->54.250.9.154:34443: i/o timeout
2024/09/19 20:31:31 group.go:263: [check] main: tls.89.node-for-bigairport.win:443(0), FAILED. error: dial tcp :0->172.234.80.13:443: i/o timeout
2024/09/19 20:31:32 server.go:99: [http] 127.0.0.1:49733 <-> checkip.amazonaws.com:443 via tls.12.node-for-bigairport.win:33443, relay error: [vmess] error in DecodeRespHeader: EOF
2024/09/19 20:31:32 group.go:263: [check] main: tls.83.node-for-bigairport.win:23443(0), FAILED. error: dial tcp :0->139.162.80.218:23443: i/o timeout
2024/09/19 20:31:34 group.go:263: [check] main: tls.100.node-for-bigairport.win:56443(0), FAILED. error: [vmess] error in DecodeRespHeader: EOF

**Comment by valucn** [comment]
Traceback (most recent call last):
  File "test_http_get.py", line 7, in <module>
    x = requests.get("https://checkip.amazonaws.com/", proxies=proxies)
  File "D:\Python\Python38\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Python\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\Python38\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Python38\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Python38\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='checkip.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by Rain-kl** [comment]
glider的forward没有配置好，所有节点全都无法通信
